### ISSUE TITLE
Dashboard design 

### ISSUE THREAD

**Issue by riyazhdholakia** [AgaKhanFoundation/WCF-iOS#159] opened 2019-05-06 13:47 UTC
1. Screen shots are attached from a 7 plus device 
https://marvelapp.com/5c70c7a/screen/54473078 (Click Dashboard)

@compnerd 
![IMG_4971](https://user-images.githubusercontent.com/33207542/57229372-e6166f00-6fe3-11e9-8ef3-f792f826d74b.png)
![Uploading IMG_4970.png…]()

**Comment by compnerd** [comment] 2019-05-11 20:14
Yes the dashboard hasn't been reimplemented.

**Comment by compnerd** [comment] 2019-05-11 20:15
Duplicate of #160

**Closed as completed by compnerd** 2019-05-11 20:15 UTC
