### ISSUE TITLE
Be able to change Personal Mile Commitment in Settings 

### ISSUE THREAD

**Issue by riyazhdholakia** [AgaKhanFoundation/WCF-iOS#248] opened 2019-09-27 19:21 UTC
If a user can change Personal Mile Commitment in Settings, if not please do not give them that look a like feature to do that. 

![image2](https://user-images.githubusercontent.com/33207542/65796313-4ac09a80-e13a-11e9-9ae3-d9161dd47a70.jpeg)

**Comment by noureend** [comment] 2019-10-05 03:39
duplicate of #277

**Closed as completed** 2019-10-05 23:02 UTC

**Comment by riyazhdholakia** [comment] 2019-10-30 12:52
![IMG_2015](https://user-images.githubusercontent.com/33207542/67859562-549b3c00-faf2-11e9-839f-6e8d34fa3dc7.png)

Bug: After you insert/enter a new value and hit save, nothing happens. Also the keyboard is covering half the screen. Need to bump the modal (pop-up) higher than keyboard.
